day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Models/AspNetCorePracticeDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace AspNetCorePractice_WebApp_MVC.Models
{
    public class AspNetCorePracticeDbContext : DbContext
    {
        public AspNetCorePracticeDbContext(DbContextOptions <AspNetCorePracticeDbContext> options) : base(options)
        {

        }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Trainer> Trainers { get; set; }
        public DbSet<Batch> Batches { get; set; }


    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Models/Batch.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AspNetCorePractice_WebApp_MVC.Models
{
    public class Batch
    {
        [Key]
        public int BatchNo { get; set; }
        public string BatchName { get; set; }
        public DateTime StartSate { get; set; }
        public DateTime EndDate { get; set; }

        public int TrainerId { get; set; }
        public Trainer Trainer { get; set;}
        public int CourseId { get; set; }
        public Course Course { get; set;}

    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Models/Course.cs
namespace AspNetCorePractice_WebApp_MVC.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string Technology { get; set; }
        public int Duration { get; set; }
        public int PriceOfCourse { get; set; }



    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Models/ErrorViewModel.cs
using System;

namespace AspNetCorePractice_WebApp_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Models/Trainer.cs
namespace AspNetCorePractice_WebApp_MVC.Models
{
    public class Trainer
    {
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }

        public string Skills { get; set; }
        public int YearOfExperience { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Controllers/BatchController.cs
using AspNetCorePractice_WebApp_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace AspNetCorePractice_WebApp_MVC.Controllers
{
    public class BatchController : Controller
    {
        private readonly AspNetCorePracticeDbContext _context;
        public BatchController(AspNetCorePracticeDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Batch> batchList = _context.Batches.ToList();
            return View(batchList);
        }
    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Controllers/CourseController.cs
using AspNetCorePractice_WebApp_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace AspNetCorePractice_WebApp_MVC.Controllers
{
    public class CourseController : Controller
    {
        private readonly AspNetCorePracticeDbContext dbContext;
        public CourseController(AspNetCorePracticeDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            List<Course> courses = dbContext.Courses.ToList();
            return View(courses);
        }
    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Controllers/HomeController.cs
using AspNetCorePractice_WebApp_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCorePractice_WebApp_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Controllers/TrainerController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCorePractice_WebApp_MVC.Models;
using System.Collections.Generic;
using System.Linq;

namespace AspNetCorePractice_WebApp_MVC.Controllers
{
    public class TrainerController : Controller
    {
        private readonly AspNetCorePracticeDbContext dbContext;
        public TrainerController(AspNetCorePracticeDbContext dbContext) {
            this.dbContext = dbContext;        
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<Trainer>  trainers = dbContext.Trainers.ToList();


            return View(trainers);  
        }
        [HttpGet]
        public IActionResult GetTrainerDetail(int trainerID)
        {
            Trainer trainer = dbContext.Trainers.Find(trainerID);
            return View(trainer);
        }
        [HttpGet]
        public IActionResult DeleteTrainer (int trainerId)
        {
            Trainer trainer = dbContext.Trainers.Find(trainerId);
            dbContext.Trainers.Remove(trainer);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddNewTrainer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewTrainer(Trainer trainer)
        {
            dbContext.Trainers.Add(trainer);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Views/Batch/Index.cshtml
@model IEnumerable< AspNetCorePractice_WebApp_MVC.Models.Batch>

<h1>Batch List</h1>

<table class="table table-bordered w-50">

    <tr>
        <th>Batch No</th>
        <th>Batch Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Course ID</th>
        <th>Trainer ID</th>
    </tr>
    @foreach (Batch item in Model)
    {
                <tr>
                    <td>@item.BatchNo</td>
                    <td>@item.BatchName</td>
                    <td>@item.StartSate</td>
                    <td>@item.EndDate</td>
                    <td>@item.CourseId</td>
                    <td>@item.TrainerId</td>
                </tr>
    }
</table>

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Views/Course/Index.cshtml
@model IEnumerable< AspNetCorePractice_WebApp_MVC.Models.Course>

<h1>Course List</h1>

<table class="table table-bordered w-50">

    <tr>
        <th>CourseId</th>
        <th>Course Name</th>
        <th>Technology</th>
        <th>Duration</th>
        <th>Price Of Course</th>
    </tr>
    @foreach (Course item in Model)
    {
            <tr>
                <td>@item.CourseId</td>
                <td>@item.CourseName</td>
                <td>@item.Technology</td>
                <td>@item.Duration</td>
                <td>@item.PriceOfCourse</td>
            </tr>
    }
</table>

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCorePractice_WebApp_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCorePractice_WebApp_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainer" asp-action="Index">Trainer</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Batch" asp-action="">Batch</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspNetCorePractice_WebApp_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

day16/AspNetCorePractice/AspNetCorePractice-WebApp-MVC/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>